const quotes: string[] = [
  "Every day is a gift worth unwrapping.",
  "You are loved more than you know.",
  "The best time to enjoy life is right now.",
  "Small steps still move you forward.",
  "Your smile brightens someone's day.",
  "Today holds something good for you.",
  "You matter to the people around you.",
  "Kindness is a language everyone understands.",
  "Each morning brings a fresh start.",
  "You've made it through every hard day so far.",
  "There is strength in simply showing up.",
  "A gentle heart is a powerful thing.",
  "The world is better because you're in it.",
  "Patience with yourself is the truest kindness.",
  "Joy can be found in the quietest moments.",
  "You are stronger than you think.",
  "Every sunset is a promise of a new dawn.",
  "Your story still has beautiful chapters ahead.",
  "A cup of tea and a kind thought go a long way.",
  "You bring warmth wherever you go.",
  "Rest is not giving up; it's taking care.",
  "Today is yours to fill with what matters most.",
  "Gratitude turns ordinary days into blessings.",
  "There is peace in taking things one day at a time.",
  "Someone is grateful to have you in their life.",
  "Even the smallest act of love makes a difference.",
  "You deserve every bit of happiness that comes your way.",
  "Life is sweeter when shared with those you love.",
  "There's beauty in a day well lived.",
  "Your presence is a gift to those around you.",
  "Hope is the gentle light that guides us forward.",
  "Every breath is a reminder of how precious life is.",
  "You've earned the right to take it easy.",
  "Laughter is good medicine at any age.",
  "The people who love you are cheering you on.",
  "Today, choose to be gentle with yourself.",
  "There is always something to look forward to.",
  "Warm memories are treasures no one can take away.",
  "You have a lifetime of wisdom to share.",
  "A peaceful day is a day well spent.",
  "You are never too old to learn something new.",
  "The simple things are often the most beautiful.",
  "You've touched more lives than you realize.",
  "Every kind word plants a seed of joy.",
  "Tomorrow is full of possibilities.",
  "You are enough, just as you are.",
  "A walk outside can lift the heaviest heart.",
  "The love you've given comes back to you.",
  "There is courage in asking for help.",
  "You deserve all the care you give to others.",
  "A good book and a quiet afternoon are treasures.",
  "Your experiences have shaped something remarkable: you.",
  "There's grace in growing older.",
  "Music has a way of healing what words cannot.",
  "You carry a light inside that never goes out.",
  "Every friendship is a gift worth cherishing.",
  "A garden teaches us patience and reward.",
  "The love you share today echoes into tomorrow.",
  "You are someone's reason to smile.",
  "Peace begins with a single deep breath.",
  "Each day you're writing your own story.",
  "The best journeys happen one step at a time.",
  "You've been through so much and still you shine.",
  "A warm conversation can brighten even a gray day.",
  "You bring something special to this world.",
  "Rest your mind; you've earned it.",
  "There's joy in looking at the world with fresh eyes.",
  "Your kindness ripples outward in ways you'll never see.",
  "Home is wherever love lives.",
  "The stars come out even after the darkest nights.",
  "You are braver than you believe.",
  "A handwritten note can make someone's whole week.",
  "Your life has meaning far beyond what you imagine.",
  "Slow mornings are a gift to be savored.",
  "The people who care about you are never far away.",
  "Healing happens in its own time.",
  "A shared meal is a shared memory.",
  "You are worthy of love and belonging.",
  "Sometimes the best thing to do is simply breathe.",
  "Your journey has been one of resilience and grace.",
  "Today's worries don't have to be tomorrow's.",
  "There is beauty in the familiar and the everyday.",
  "A sunrise is nature's way of saying keep going.",
  "You have more good days ahead of you.",
  "Gentleness is its own form of strength.",
  "The love in your heart is your greatest treasure.",
  "A moment of stillness can restore so much.",
  "You've already overcome more than you give yourself credit for.",
  "Every day above ground is a good day.",
  "The sound of birdsong is nature's lullaby.",
  "You are a chapter in someone else's favorite story.",
  "There's always time for one more cup of tea.",
  "Your family thinks of you with love.",
  "Life is a collection of beautiful, ordinary moments.",
  "No act of kindness, however small, is ever wasted.",
  "A deep breath is the simplest form of self-care.",
  "You are the calm in someone's storm.",
  "Happiness looks different at every age, and that's okay.",
  "Your wisdom is a gift that keeps on giving.",
  "There is always room for one more smile.",
  "The love you've built is your legacy.",
  "A sunny window and a warm blanket heal many things.",
  "Today is a day worth celebrating, just because.",
  "The sound of rain can be the most peaceful music.",
  "You are a thread woven into many hearts.",
  "Taking care of yourself is never selfish.",
  "Your memories are a library no one else can own.",
  "Every kind deed writes itself into history.",
  "The world needs the warmth only you can give.",
  "Comfort comes in knowing you are not alone.",
  "A flower doesn't rush to bloom, and neither should you.",
  "Your laughter is someone's favorite sound.",
  "There is strength in letting yourself be cared for.",
  "Today holds at least one reason to be glad.",
  "The tea is warm, the day is yours.",
  "You've planted seeds of goodness all your life.",
  "Some of the best days are the quiet ones.",
  "You bring comfort to those who know you.",
  "Life has a way of surprising us with joy.",
  "Your hands have held many things with love.",
  "A nap is a perfectly good use of the afternoon.",
  "The people you've helped remember your kindness.",
  "There's no deadline on happiness.",
  "You are treasured.",
];

export function getQuoteOfTheDay(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return quotes[dayOfYear % quotes.length];
}
