// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sos-emergency-page/CalmHero.tsx": () => import("../components/mockups/sos-emergency-page/CalmHero.tsx"),
  "./components/mockups/sos-emergency-page/EditorialTimeline.tsx": () => import("../components/mockups/sos-emergency-page/EditorialTimeline.tsx"),
  "./components/mockups/sos-emergency-page/MapForward.tsx": () => import("../components/mockups/sos-emergency-page/MapForward.tsx"),
  "./components/mockups/sos-emergency-page/TriageFirst.tsx": () => import("../components/mockups/sos-emergency-page/TriageFirst.tsx")
};
